var talks = [
	{
		'title': 'From Physics-Based Control to Controllable, Adaptive, and Expressive Character Animation',
		'year': 2026,
		'conference_journal_full': 'Invited talk, 2026 Asia Graphics Workshop on Intelligent Graphics, April 2026',
		'additional': '<a href="https://gitcgr.hanyang.ac.kr/talks/2026-AG-physics-to-more.pdf" rel="noopener noreferrer" target="_blank">[slides]</a>',
		'type': 'talk',
	},
	{
		'title': 'Technology and Art: Where Different Creative Practices Meet',
		'year': 2025,
		'conference_journal_full': 'Invited talk, 20th Anniversary Symposium of the Research Institute of Art and Technology, Hanyang University, December 2025',
		'additional': '<a href="https://gitcgr.hanyang.ac.kr/talks/2025-tech-art.pdf" rel="noopener noreferrer" target="_blank">[slides (Korean)]</a>',
		'type': 'talk',
	},
	{
		'title': 'Human Simulation Research: Toward Physically and Biomechanically Grounded Motion',
		'year': 2025,
		'conference_journal_full': 'Invited talk, ETRI, November 2025',
		'additional': '',
		'type': 'talk',
	},
	{
		'title': 'Learning How to Move',
		'year': 2024,
		'conference_journal_full': 'Invited talk, Hanyang AI Convergence Research Forum, January 2024',
		'additional': '',
		'type': 'talk',
	},
	{
		'title': 'Character Animation Basics',
		'representative_img': 'assets/publications/domestic/2022-kcgs-summerschool-character_animation_basics.png',
		'year': 2022,
		'authors': '이윤상',
		'conference_journal_full': 'Tutorial, KCGS 2022 Summer School, July 2022',
		'additional': '<a href="https://gitcgr.hanyang.ac.kr/talks/2022-kcgs-summerschool-character_animation_basics-public.pdf" rel="noopener noreferrer" target="_blank">[slides]</a>',
		'type': 'talk',
	},
	//{
		//'title': 'Character Animation Basics',
		//'representative_img': 'assets/publications/domestic/2022-kcgs-summerschool-character_animation_basics.png',
		//'year': 2022,
		//'authors': '이윤상',
		//'conference_journal_full': '한국컴퓨터그래픽스학회 2022년 학술대회 여름학교, 2022.07.',
		//'additional': '<a href="https://gitcgr.hanyang.ac.kr/publications/domestic/2022-kcgs-summerschool-character_animation_basics-public.pdf" rel="noopener noreferrer" target="_blank">[slides]</a>',
		//'type': 'talk',
	//},
	{
		'title': 'Physics Fundamentals for Walking Simulation',
		'representative_img': 'assets/publications/domestic/2019-orthopaedic-walking-basic.png',
		'year': 2019,
		'authors': '이윤상',
		'conference_journal_full': 'Invited talk, 2019 SNU Orthopaedic Update(II): Pediatric Orthopaedics, SNUBH, June 2019',
		'additional': '<a href="https://gitcgr.hanyang.ac.kr/talks/2019-orthopaedic-walking-basic-slides.pdf" rel="noopener noreferrer" target="_blank">[slides (Korean)]</a>'+
					' <a href="https://gitcgr.hanyang.ac.kr/talks/2019-orthopaedic-walking-basic.pdf" rel="noopener noreferrer" target="_blank">[article (Korean)]</a>',
		'type': 'talk',
	},
	//{
		//'title': '보행 시뮬레이션을 위한 물리의 기초',
		//'representative_img': 'assets/publications/domestic/2019-orthopaedic-walking-basic.png',
		//'year': 2019,
		//'authors': '이윤상',
		//'conference_journal_full': 'Proceeding of 2019 SNU Orthopaedic Update(II): Pediatric Orthopaedics, 115-122, 2019.06.',
		//'additional': '<a href="https://gitcgr.hanyang.ac.kr/publications/domestic/2019-orthopaedic-walking-basic-slides.pdf" rel="noopener noreferrer" target="_blank">[slides]</a>'+
					//' <a href="https://gitcgr.hanyang.ac.kr/publications/domestic/2019-orthopaedic-walking-basic.pdf" rel="noopener noreferrer" target="_blank">[article]</a>',
		//'type': 'talk',
	//},
	{
		'title': 'Make It Walk!: Locomotion Control',
		'representative_img': 'assets/publications/domestic/2016-kcgs-make-it-walk.png',
		'year': 2016,
		'authors': 'Yoonsang Lee',
		'conference_journal_full': 'Invited Talk, KCGS 2016, July 2016',
		'additional': '<a href="https://gitcgr.hanyang.ac.kr/talks/2016-kcgs-make-it-walk.pdf" rel="noopener noreferrer" target="_blank">[slides]</a>',
		'type': 'talk',
	},
	//{
		//'title': 'Make It Walk!: Locomotion Control',
		//'representative_img': 'assets/publications/domestic/2016-kcgs-make-it-walk.png',
		//'year': 2016,
		//'authors': '이윤상',
		//'conference_journal_full': '한국컴퓨터그래픽스학회 2016년 학술대회 초청강연, 2016.07.',
		//'additional': '<a href="https://gitcgr.hanyang.ac.kr/publications/domestic/2016-kcgs-make-it-walk.pdf" rel="noopener noreferrer" target="_blank">[slides]</a>',
		//'type': 'talk',
	//},
]
